---
title: "Inequality PSet 1 - Question #6 (code part)"
author: "JDu"
date: "`r lubridate::today()`"
output: pdf_document
---

## Load necessary libraries
```{r}
library(tidyverse)
library(lubridate)
library(lfe)
library(stats)
#library(tsibble)
library(ivreg)
library(broom)

theme_set(theme_minimal())
```

## could write 6c in .Rmd - but should do 6a & 6b on paper

# Question 6d

## Question 6d(i): Construct the outcome variables

```{r}
q1 <- read_csv("./DataExercise_IV/pset_iv_data.csv") %>%
  rename(pop = Pop, earnPOW = EarnPOW, man = Manufact)

# 6d(i).A: transform var by taking nat logs
q1 <- q1 %>%
  mutate(lnpay = log(pay),
         lnpop = log(pop),
         lnearnPOW = log(earnPOW), # county earnings
         lndSSI = log(dSSI)) # SSI payments 
# BE CAREFUL - MAYBE SHOULD KEEP ORIGINAL PAY VAR & NOT OVERWRITE W/ LOG VERSIONS?

# 6d(i).B: construct log diff
q1 <- q1 %>%
  group_by(fips) %>% #DELETE HERE IF NEEDED
  mutate(lagpay = lag(lnpay, n = 1),
         lagpop = lag(lnpop, n = 1),
         lagearnPOW = lag(lnearnPOW, n = 1),
         lagdSSI = lag(lndSSI, n = 1)) %>%
  mutate(diff_pay = lnpay - lagpay,
         diff_pop = lnpop - lagpop,
         diff_earnPOW = lnearnPOW - lagearnPOW,
         diff_dSSI = lndSSI - lagdSSI) 
  
q1_oof <- q1 %>%
  group_by(fips) %>%
  mutate(lagpay = lag(lnpay, n = 1),
         lagpop = lag(lnpop, n = 1),
         lagearnPOW = lag(lnearnPOW, n = 1),
         lagdSSI = lag(lndSSI, n = 1)) %>%
  mutate(diff_pay = lnpay - lagpay,
         diff_pop = lnpop - lagpop,
         diff_earnPOW = lnearnPOW - lagearnPOW,
         diff_dSSI = lndSSI - lagdSSI) 

# 6d(i).C: construct var that is fraction of county earnings from manufacturing in 1969
q1 %>%
  filter(year == 1969) %>%
  #pull(man)
  mutate(man_1969 = man/earnPOW)

### ASK ELLIE: fraction of earnings - is it saying "find the fraction of county earnings in every yr compared to the 1969 value of manufacturing)?
# if so, do it like this??
man_value_1969 <- 
  q1 %>%
  filter(year == 1969) %>%
  select(man, fips) 

q1 <- 
man_value_1969 %>%
  left_join(q1, by = "fips") %>%
  mutate(frac_earn = man.x/earnPOW) 
```

## Question 6d(ii): Construct the instruments

```{r}
# construct coal price
q1 <- q1 %>%
  mutate(coalprice = pcoalyr/pyr)

# construct change in coal reserves
q1 <- q1 %>%
  group_by(fips) %>%
  mutate(ln_coalprice = log(coalprice),
         lag_coalprice = lag(ln_coalprice, n = 1),
         diff_coalprice = ln_coalprice - lag_coalprice) %>%
  mutate(ln_coalres = log(coalres)) %>%
  mutate(valchange_cr = 
           if_else(coalres > 0,
                   diff_coalprice * ln_coalres, 0)) 



q1 %>%
  filter(valchange_cr < 0)
```


## Question 6d(iii): Construct the outcome variables

```{r}
library(moderndive) #https://cran.r-project.org/web/packages/moderndive/vignettes/why-moderndive.html
library(lfe) #felm - multiple group fixed effs? - 
#https://cran.r-project.org/web/packages/lfe/lfe.pdf (pg. 19)
#library(robustbase) 
#use lmrob just like lm - https://www.brodrigues.co/blog/2018-07-08-rob_stderr/
library(lmtest)
library(sandwich)
# https://www.r-econometrics.com/methods/hcrobusterrors/

#other qs: 1969 q, why ellie & i get diff rows for coal res change in value
# DOES YEAR*FIPS qualify as control var

ols_ssi_c <- lm(diff_dSSI ~ diff_earnPOW + year*fips + msa + lnpop + diff_pop + frac_earn, data = q1)

ols_ssi_nc <- lm(diff_dSSI ~ diff_earnPOW + year*fips, data = q1)

ols_di_c <- lm(diff_dSSI ~ diff_earnPOW + year*fips + msa + lnpop + diff_pop + frac_earn, data = q1)

ols_di_c <- lm(diff_dSSI ~ diff_earnPOW + year*fips, data = q1)

get_regression_table(ols_ssi_c)
get_regression_table(ols_ssi_nc)
get_regression_table(ols_di_c)
get_regression_table(ols_di_nc)

# trying to get robust SE
get_regression_table(ols_ssi_c) #regular SE
coeftest(ols_ssi_c, vcov = vcovHC(ols_ssi_c, type = "HC0")) %>%
  broom::tidy() #THIS WORKS! do same for rest
```


## Question 6d(i): Construct the outcome variables

```{r}
```


